spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018,localhost:27019,localhost:27020/?replicaSet=myReplicaSet&readPreference=secondaryPreferred
      database: tasks
server:
  port: 8080

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
