spring:
  data:
    mongodb:
      uri: mongodb://localhost:27023/
      database: tasks

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
